---

- name: Ensure base Radarr directory exists
  ansible.builtin.file:
    path: "{{ radarr_docker_base_directory }}"
    state: 'directory'
    owner: "{{ radarr_docker_user }}"
    group: "{{ radarr_docker_user }}"
    mode: '0755'

- name: Ensure Radarr compose file is present
  ansible.builtin.template:
    src: 'compose.yml.j2'
    dest: "{{ radarr_docker_base_directory }}/compose.yml"
    owner: "{{ radarr_docker_user }}"
    group: "{{ radarr_docker_user }}"
    mode: '0644'
    backup: true
  register: radarr_docker_compose_template_result

- name: Ensure Radarr compose project is deployed
  community.docker.docker_compose_v2:
    project_src: "{{ radarr_docker_base_directory }}"
    state: 'present'
    pull: "{{ 'always' if radarr_docker_update_image else radarr_docker_pull_policy }}"
    recreate: "{{ 'always' if (radarr_docker_compose_template_result.changed or radarr_docker_update_image) else 'auto' }}"
    remove_orphans: true
