---

- name: Ensure base Radarr directory exists
  ansible.builtin.file:
    path: "{{ radarr_docker_base_directory }}"
    state: 'directory'
    owner: "{{ radarr_docker_user }}"
    group: "{{ radarr_docker_user }}"
    mode: '0755'
  tags:
    - radarr
    - radarr_setup

- name: Ensure Radarr compose file is present
  ansible.builtin.template:
    src: 'compose.yml.j2'
    dest: "{{ radarr_docker_base_directory }}/compose.yml"
    owner: "{{ radarr_docker_user }}"
    group: "{{ radarr_docker_user }}"
    mode: '0644'
    backup: true
  register: radarr_docker_compose_template_result
  tags:
    - radarr
    - radarr_config

- name: Ensure Radarr compose project is deployed
  community.docker.docker_compose_v2:
    project_src: "{{ radarr_docker_base_directory }}"
    state: 'present'
    recreate: "{{ 'always' if (radarr_docker_compose_template_result.changed) else 'auto' }}"
    remove_orphans: true
  tags:
    - radarr
    - radarr_deploy
